import random

# Diccionario con 300 frases únicas de felicitaciones de cumpleaños
frases_cumpleanos = {
    1: "¡Feliz cumpleaños! Que todos tus sueños se hagan realidad.",
    2: "¡Que tengas un día lleno de alegría y sorpresas maravillosas!",
    3: "¡Felicidades en tu día especial! Que la felicidad te acompañe siempre.",
    4: "¡Feliz cumpleaños! Que este nuevo año de vida sea el mejor de todos.",
    5: "¡Que celebres muchos cumpleaños más llenos de salud y amor!",
    6: "¡Feliz cumpleaños! Eres una persona muy especial y mereces lo mejor.",
    7: "¡Que tu día esté lleno de risas, abrazos y buenos momentos!",
    8: "¡Felicidades! Que sigas cumpliendo años con la misma energía y alegría.",
    9: "¡Feliz cumpleaños! Que la vida te regale momentos inolvidables.",
    10: "¡Que este cumpleaños sea el inicio de 365 días maravillosos!",
    11: "¡Feliz cumpleaños! Que tu sonrisa ilumine cada día del año.",
    12: "¡Que tu cumpleaños esté lleno de amor, paz y prosperidad!",
    13: "¡Felicidades en tu día! Eres un regalo para todos los que te conocen.",
    14: "¡Feliz cumpleaños! Que sigas creciendo en sabiduría y felicidad.",
    15: "¡Que tu nuevo año de vida esté lleno de aventuras increíbles!",
    16: "¡Feliz cumpleaños! Que cada deseo que pidas se convierta en realidad.",
    17: "¡Que la felicidad te acompañe hoy y siempre! ¡Feliz cumpleaños!",
    18: "¡Felicidades! Que este año te traiga todo lo que tu corazón desea.",
    19: "¡Feliz cumpleaños! Que tu día sea tan especial como tú lo eres.",
    20: "¡Que celebres este día rodeado de las personas que más amas!",
    21: "¡Feliz cumpleaños! Que la vida te sonría cada día del año.",
    22: "¡Que tu cumpleaños sea el mejor de todos! ¡Muchas felicidades!",
    23: "¡Feliz cumpleaños! Que sigas siendo esa persona maravillosa que eres.",
    24: "¡Que este nuevo ciclo esté lleno de bendiciones y éxitos!",
    25: "¡Felicidades! Que tu día sea tan brillante como tu espíritu.",
    26: "¡Feliz cumpleaños! Que cada momento de este día sea memorable.",
    27: "¡Que tu cumpleaños esté lleno de sorpresas agradables y alegría!",
    28: "¡Feliz cumpleaños! Que la fortuna te acompañe en este nuevo año.",
    29: "¡Que celebres muchos cumpleaños más con salud y felicidad!",
    30: "¡Felicidades! Que tu vida siga siendo tan hermosa como hasta ahora.",
    31: "¡Feliz cumpleaños! Que tus días estén llenos de luz y esperanza.",
    32: "¡Que este cumpleaños marque el inicio de grandes logros!",
    33: "¡Feliz cumpleaños! Eres una bendición para todos nosotros.",
    34: "¡Que tu día esté lleno de amor, risas y momentos especiales!",
    35: "¡Felicidades en tu cumpleaños! Que sigas brillando como siempre.",
    36: "¡Feliz cumpleaños! Que cada día del año sea una celebración.",
    37: "¡Que tu nuevo año de vida esté lleno de oportunidades maravillosas!",
    38: "¡Feliz cumpleaños! Que la alegría sea tu compañera fiel este año.",
    39: "¡Que celebres este día con toda la emoción que mereces!",
    40: "¡Felicidades! Que tu cumpleaños sea tan increíble como tú.",
    41: "¡Feliz cumpleaños! Que sigas cosechando éxitos y alegrías.",
    42: "¡Que tu día especial esté lleno de magia y felicidad!",
    43: "¡Feliz cumpleaños! Que este año te traiga paz y prosperidad.",
    44: "¡Que celebres muchos años más rodeado de amor y cariño!",
    45: "¡Felicidades! Que tu vida siga siendo un ejemplo de bondad.",
    46: "¡Feliz cumpleaños! Que cada momento de este día sea perfecto.",
    47: "¡Que tu cumpleaños esté lleno de abrazos y buenos deseos!",
    48: "¡Feliz cumpleaños! Que la vida te regale todo lo que mereces.",
    49: "¡Que este nuevo ciclo esté lleno de sueños cumplidos!",
    50: "¡Felicidades! Que tu día sea tan especial como tu presencia.",
    51: "¡Feliz cumpleaños! Que sigas siendo luz en la vida de otros.",
    52: "¡Que tu cumpleaños esté lleno de momentos inolvidables!",
    53: "¡Feliz cumpleaños! Que cada día sea mejor que el anterior.",
    54: "¡Que celebres este día con toda la alegría del mundo!",
    55: "¡Felicidades! Que tu año esté lleno de salud y bienestar.",
    56: "¡Feliz cumpleaños! Que tus metas se conviertan en realidades.",
    57: "¡Que tu día especial esté lleno de amor y gratitud!",
    58: "¡Feliz cumpleaños! Que la felicidad nunca se aleje de ti.",
    59: "¡Que este año te traiga nuevas y emocionantes aventuras!",
    60: "¡Felicidades! Que tu cumpleaños sea el inicio de algo grandioso.",
    61: "¡Feliz cumpleaños! Que sigas iluminando el mundo con tu sonrisa.",
    62: "¡Que tu día esté lleno de regalos, torta y mucha diversión!",
    63: "¡Feliz cumpleaños! Que cada deseo se haga realidad este año.",
    64: "¡Que celebres este día con las personas que más quieres!",
    65: "¡Felicidades! Que tu vida siga siendo un camino de éxitos.",
    66: "¡Feliz cumpleaños! Que este año sea mejor que todos los anteriores.",
    67: "¡Que tu cumpleaños esté lleno de sorpresas maravillosas!",
    68: "¡Feliz cumpleaños! Que la dicha te acompañe cada día.",
    69: "¡Que este nuevo año de vida sea pleno y satisfactorio!",
    70: "¡Felicidades! Que tu día sea tan hermoso como tu corazón.",
    71: "¡Feliz cumpleaños! Que sigas creciendo en todos los aspectos.",
    72: "¡Que tu cumpleaños esté lleno de risas y buenos recuerdos!",
    73: "¡Feliz cumpleaños! Que la vida te siga bendiciendo abundantemente.",
    74: "¡Que celebres muchos años más con la misma vitalidad!",
    75: "¡Felicidades! Que tu día sea una celebración de tu existencia.",
    76: "¡Feliz cumpleaños! Que cada momento del año sea especial.",
    77: "¡Que tu nuevo ciclo esté lleno de amor y comprensión!",
    78: "¡Feliz cumpleaños! Que tus sueños más anhelados se cumplan.",
    79: "¡Que tu día especial esté lleno de música y alegría!",
    80: "¡Felicidades! Que la vida te recompense por tu bondad.",
    81: "¡Feliz cumpleaños! Que sigas siendo esa persona inspiradora.",
    82: "¡Que tu cumpleaños esté lleno de cariño y aprecio!",
    83: "¡Feliz cumpleaños! Que este año te traiga mucha sabiduría.",
    84: "¡Que celebres este día con toda la emoción que sientes!",
    85: "¡Felicidades! Que tu año esté lleno de momentos significativos.",
    86: "¡Feliz cumpleaños! Que la fortuna te sonría siempre.",
    87: "¡Que tu día especial esté lleno de bendiciones divinas!",
    88: "¡Feliz cumpleaños! Que cada día sea una nueva oportunidad.",
    89: "¡Que este nuevo año de vida supere todas tus expectativas!",
    90: "¡Felicidades! Que tu cumpleaños sea memorable y feliz.",
    91: "¡Feliz cumpleaños! Que sigas construyendo tu mejor versión.",
    92: "¡Que tu día esté lleno de personas que te valoran!",
    93: "¡Feliz cumpleaños! Que la paz reine en tu corazón este año.",
    94: "¡Que celebres muchos cumpleaños más con gran entusiasmo!",
    95: "¡Felicidades! Que tu vida siga siendo un testimonio de amor.",
    96: "¡Feliz cumpleaños! Que cada instante de hoy sea especial.",
    97: "¡Que tu cumpleaños esté lleno de detalles hermosos!",
    98: "¡Feliz cumpleaños! Que la vida te regale muchas alegrías.",
    99: "¡Que este nuevo ciclo esté lleno de logros importantes!",
    100: "¡Felicidades! Que tu día sea tan único como tú lo eres.",
    101: "¡Feliz cumpleaños! Que sigas marcando una diferencia positiva.",
    102: "¡Que tu cumpleaños esté lleno de amor incondicional!",
    103: "¡Feliz cumpleaños! Que cada día te traiga nueva felicidad.",
    104: "¡Que celebres este día con mucha gratitud y alegría!",
    105: "¡Felicidades! Que tu año esté lleno de experiencias enriquecedoras.",
    106: "¡Feliz cumpleaños! Que tus proyectos se realicen exitosamente.",
    107: "¡Que tu día especial esté lleno de momentos mágicos!",
    108: "¡Feliz cumpleaños! Que la vida te devuelva todo lo bueno que das.",
    109: "¡Que este año te traiga mucha paz interior y exterior!",
    110: "¡Felicidades! Que tu cumpleaños sea el mejor de todos los tiempos.",
    111: "¡Feliz cumpleaños! Que sigas siendo un ejemplo a seguir.",
    112: "¡Que tu día esté lleno de abrazos sinceros y cálidos!",
    113: "¡Feliz cumpleaños! Que la prosperidad llegue a tu vida.",
    114: "¡Que celebres muchos años más con salud y alegría!",
    115: "¡Felicidades! Que tu vida siga llena de propósito y sentido.",
    116: "¡Feliz cumpleaños! Que cada deseo que pidas se materialice.",
    117: "¡Que tu cumpleaños esté lleno de sonrisas genuinas!",
    118: "¡Feliz cumpleaños! Que la vida te sorprenda gratamente.",
    119: "¡Que este nuevo ciclo esté lleno de aprendizajes valiosos!",
    120: "¡Felicidades! Que tu día sea una celebración de la vida.",
    121: "¡Feliz cumpleaños! Que sigas contagiando felicidad a todos.",
    122: "¡Que tu cumpleaños esté lleno de buenos augurios!",
    123: "¡Feliz cumpleaños! Que cada momento del año sea brillante.",
    124: "¡Que celebres este día con mucha ilusión y esperanza!",
    125: "¡Felicidades! Que tu año esté lleno de satisfacciones personales.",
    126: "¡Feliz cumpleaños! Que tus anhelos se conviertan en logros.",
    127: "¡Que tu día especial esté lleno de cosas maravillosas!",
    128: "¡Feliz cumpleaños! Que la vida te premie por tu esfuerzo.",
    129: "¡Que este año te traiga renovadas energías y optimismo!",
    130: "¡Felicidades! Que tu cumpleaños sea extraordinario y especial.",
    131: "¡Feliz cumpleaños! Que sigas alcanzando todas tus metas.",
    132: "¡Que tu día esté lleno de reconocimiento y aprecio!",
    133: "¡Feliz cumpleaños! Que la armonía reine en tu vida.",
    134: "¡Que celebres muchos cumpleaños más con gran felicidad!",
    135: "¡Felicidades! Que tu vida siga siendo plena y satisfactoria.",
    136: "¡Feliz cumpleaños! Que cada día sea una aventura nueva.",
    137: "¡Que tu cumpleaños esté lleno de momentos emotivos!",
    138: "¡Feliz cumpleaños! Que la vida te colme de bendiciones.",
    139: "¡Que este nuevo ciclo esté lleno de prosperidad y abundancia!",
    140: "¡Felicidades! Que tu día sea tan radiante como tu espíritu.",
    141: "¡Feliz cumpleaños! Que sigas siendo fuente de inspiración.",
    142: "¡Que tu cumpleaños esté lleno de afecto y compañía!",
    143: "¡Feliz cumpleaños! Que cada día te acerque a tus sueños.",
    144: "¡Que celebres este día con todo el amor que mereces!",
    145: "¡Felicidades! Que tu año esté lleno de momentos memorables.",
    146: "¡Feliz cumpleaños! Que tus esperanzas se hagan realidad.",
    147: "¡Que tu día especial esté lleno de buena energía!",
    148: "¡Feliz cumpleaños! Que la vida te regale nuevas oportunidades.",
    149: "¡Que este año te traiga mucha tranquilidad y balance!",
    150: "¡Felicidades! Que tu cumpleaños sea inolvidable y perfecto.",
    151: "¡Feliz cumpleaños! Que sigas dejando huella en los demás.",
    152: "¡Que tu día esté lleno de celebración y júbilo!",
    153: "¡Feliz cumpleaños! Que la sabiduría te acompañe siempre.",
    154: "¡Que celebres muchos años más con mucha vitalidad!",
    155: "¡Felicidades! Que tu vida siga siendo un jardín florido.",
    156: "¡Feliz cumpleaños! Que cada sueño se convierta en proyecto.",
    157: "¡Que tu cumpleaños esté lleno de detalles especiales!",
    158: "¡Feliz cumpleaños! Que la vida te devuelva multiplicado tu amor.",
    159: "¡Que este nuevo ciclo esté lleno de crecimiento personal!",
    160: "¡Felicidades! Que tu día sea una fiesta llena de alegría.",
    161: "¡Feliz cumpleaños! Que sigas siendo ese ser maravilloso.",
    162: "¡Que tu cumpleaños esté lleno de gratitud y felicidad!",
    163: "¡Feliz cumpleaños! Que cada momento del año sea glorioso.",
    164: "¡Que celebres este día con mucha emoción y entusiasmo!",
    165: "¡Felicidades! Que tu año esté lleno de descubrimientos increíbles.",
    166: "¡Feliz cumpleaños! Que tus ilusiones se materialicen pronto.",
    167: "¡Que tu día especial esté lleno de sorpresas positivas!",
    168: "¡Feliz cumpleaños! Que la vida te dé todo lo que esperas.",
    169: "¡Que este año te traiga mucha claridad y dirección!",
    170: "¡Felicidades! Que tu cumpleaños sea espectacular y único.",
    171: "¡Feliz cumpleaños! Que sigas brillando con luz propia.",
    172: "¡Que tu día esté lleno de momentos de felicidad pura!",
    173: "¡Feliz cumpleaños! Que la plenitud sea tu estado natural.",
    174: "¡Que celebres muchos cumpleaños más con gran vigor!",
    175: "¡Felicidades! Que tu vida siga siendo una obra de arte.",
    176: "¡Feliz cumpleaños! Que cada objetivo se convierta en victoria.",
    177: "¡Que tu cumpleaños esté lleno de cosas hermosas!",
    178: "¡Feliz cumpleaños! Que la vida te recompense generosamente.",
    179: "¡Que este nuevo ciclo esté lleno de realizaciones personales!",
    180: "¡Felicidades! Que tu día sea tan especial como tu alma.",
    181: "¡Feliz cumpleaños! Que sigas esparciendo amor por doquier.",
    182: "¡Que tu cumpleaños esté lleno de celebración y gozo!",
    183: "¡Feliz cumpleaños! Que cada día te sorprenda positivamente.",
    184: "¡Que celebres este día con toda la alegría posible!",
    185: "¡Felicidades! Que tu año esté lleno de triunfos personales.",
    186: "¡Feliz cumpleaños! Que tus deseos más profundos se cumplan.",
    187: "¡Que tu día especial esté lleno de energía positiva!",
    188: "¡Feliz cumpleaños! Que la vida te regale salud y amor.",
    189: "¡Que este año te traiga mucha creatividad y pasión!",
    190: "¡Felicidades! Que tu cumpleaños sea magnifico y grandioso.",
    191: "¡Feliz cumpleaños! Que sigas siendo esa persona admirable.",
    192: "¡Que tu día esté lleno de buenos momentos compartidos!",
    193: "¡Feliz cumpleaños! Que la felicidad te encuentre cada día.",
    194: "¡Que celebres muchos años más con mucho ánimo!",
    195: "¡Felicidades! Que tu vida siga siendo una aventura hermosa.",
    196: "¡Feliz cumpleaños! Que cada paso te lleve al éxito.",
    197: "¡Que tu cumpleaños esté lleno de buenos deseos realizados!",
    198: "¡Feliz cumpleaños! Que la vida te abra puertas nuevas.",
    199: "¡Que este nuevo ciclo esté lleno de experiencias positivas!",
    200: "¡Felicidades! Que tu día sea una celebración de tu esencia.",
    201: "¡Feliz cumpleaños! Que sigas compartiendo tu luz con todos.",
    202: "¡Que tu cumpleaños esté lleno de alegrías inesperadas!",
    203: "¡Feliz cumpleaños! Que cada momento sea digno de recordar.",
    204: "¡Que celebres este día con mucha pasión y amor!",
    205: "¡Felicidades! Que tu año esté lleno de satisfacciones profundas.",
    206: "¡Feliz cumpleaños! Que tus metas sean alcanzadas con éxito.",
    207: "¡Que tu día especial esté lleno de magia y encanto!",
    208: "¡Feliz cumpleaños! Que la vida te premie con felicidad duradera.",
    209: "¡Que este año te traiga mucha estabilidad y progreso!",
    210: "¡Felicidades! Que tu cumpleaños sea fenomenal y hermoso.",
    211: "¡Feliz cumpleaños! Que sigas siendo un regalo para el mundo.",
    212: "¡Que tu día esté lleno de afecto y reconocimiento!",
    213: "¡Feliz cumpleaños! Que la serenidad habite en tu corazón.",
    214: "¡Que celebres muchos cumpleaños más con gran entusiasmo!",
    215: "¡Felicidades! Que tu vida siga siendo un camino de luz.",
    216: "¡Feliz cumpleaños! Que cada aspiración se haga realidad.",
    217: "¡Que tu cumpleaños esté lleno de momentos significativos!",
    218: "¡Feliz cumpleaños! Que la vida te bendiga abundantemente.",
    219: "¡Que este nuevo ciclo esté lleno de éxitos y victorias!",
    220: "¡Felicidades! Que tu día sea tan bello como tu corazón.",
    221: "¡Feliz cumpleaños! Que sigas irradiando positividad siempre.",
    222: "¡Que tu cumpleaños esté lleno de amor verdadero!",
    223: "¡Feliz cumpleaños! Que cada día te traiga nueva inspiración.",
    224: "¡Que celebres este día con toda la gratitud del mundo!",
    225: "¡Felicidades! Que tu año esté lleno de aventuras emocionantes.",
    226: "¡Feliz cumpleaños! Que tus planes se desarrollen perfectamente.",
    227: "¡Que tu día especial esté lleno de buenas vibras!",
    228: "¡Feliz cumpleaños! Que la vida te sorprenda cada día.",
    229: "¡Que este año te traiga mucha felicidad y contentamiento!",
    230: "¡Felicidades! Que tu cumpleaños sea maravilloso y alegre.",
    231: "¡Feliz cumpleaños! Que sigas creciendo en amor y bondad.",
    232: "¡Que tu día esté lleno de celebraciones y risas!",
    233: "¡Feliz cumpleaños! Que la fortuna te acompañe este año.",
    234: "¡Que celebres muchos años más con mucha energía!",
    235: "¡Felicidades! Que tu vida siga siendo una bendición.",
    236: "¡Feliz cumpleaños! Que cada meta sea superada con éxito.",
    237: "¡Que tu cumpleaños esté lleno de regalos especiales!",
    238: "¡Feliz cumpleaños! Que la vida te colme de satisfacciones.",
    239: "¡Que este nuevo ciclo esté lleno de momentos felices!",
    240: "¡Felicidades! Que tu día sea una fiesta memorable.",
    241: "¡Feliz cumpleaños! Que sigas siendo esa persona excepcional.",
    242: "¡Que tu cumpleaños esté lleno de paz y armonía!",
    243: "¡Feliz cumpleaños! Que cada día sea mejor que el previo.",
    244: "¡Que celebres este día con mucho amor y cariño!",
    245: "¡Felicidades! Que tu año esté lleno de nuevas oportunidades.",
    246: "¡Feliz cumpleaños! Que tus sueños cobren vida este año.",
    247: "¡Que tu día especial esté lleno de momentos únicos!",
    248: "¡Feliz cumpleaños! Que la vida te regale mucha prosperidad.",
    249: "¡Que este año te traiga mucha alegría y satisfacción!",
    250: "¡Felicidades! Que tu cumpleaños sea excepcional y brillante.",
    251: "¡Feliz cumpleaños! Que sigas inspirando a quienes te rodean.",
    252: "¡Que tu día esté lleno de buenos recuerdos y nuevos comienzos!",
    253: "¡Feliz cumpleaños! Que la tranquilidad sea tu compañera.",
    254: "¡Que celebres muchos cumpleaños más con mucha salud!",
    255: "¡Felicidades! Que tu vida siga siendo una historia hermosa.",
    256: "¡Feliz cumpleaños! Que cada esfuerzo tenga su recompensa.",
    257: "¡Que tu cumpleaños esté lleno de detalles bonitos!",
    258: "¡Feliz cumpleaños! Que la vida te regale todo lo que necesitas.",
    259: "¡Que este nuevo ciclo esté lleno de bendiciones infinitas!",
    260: "¡Felicidades! Que tu día sea tan especial como tu presencia.",
    261: "¡Feliz cumpleaños! Que sigas siendo luz en la oscuridad.",
    262: "¡Que tu cumpleaños esté lleno de amor y comprensión!",
    263: "¡Feliz cumpleaños! Que cada instante valga la pena.",
    264: "¡Que celebres este día con mucha ilusión y esperanza!",
    265: "¡Felicidades! Que tu año esté lleno de logros importantes.",
    266: "¡Feliz cumpleaños! Que tus proyectos florezcan exitosamente.",
    267: "¡Que tu día especial esté lleno de cosas increíbles!",
    268: "¡Feliz cumpleaños! Que la vida te devuelva todo lo bueno.",
    269: "¡Que este año te traiga mucha sabiduría y crecimiento!",
    270: "¡Felicidades! Que tu cumpleaños sea fantástico y divertido.",
    271: "¡Feliz cumpleaños! Que sigas siendo esa fuerza positiva.",
    272: "¡Que tu día esté lleno de sorpresas agradables!",
    273: "¡Feliz cumpleaños! Que la dicha inunde tu vida.",
    274: "¡Que celebres muchos años más con gran optimismo!",
    275: "¡Felicidades! Que tu vida siga siendo un ejemplo de amor.",
    276: "¡Feliz cumpleaños! Que cada deseo se materialice pronto.",
    277: "¡Que tu cumpleaños esté lleno de celebración y gozo!",
    278: "¡Feliz cumpleaños! Que la vida te sorprenda gratamente.",
    279: "¡Que este nuevo ciclo esté lleno de aventuras maravillosas!",
    280: "¡Felicidades! Que tu día sea una celebración de la alegría.",
    281: "¡Feliz cumpleaños! Que sigas contagiando tu energía positiva.",
    282: "¡Que tu cumpleaños esté lleno de momentos inolvidables!",
    283: "¡Feliz cumpleaños! Que cada día te acerque a la felicidad plena.",
    284: "¡Que celebres este día con todo el amor que hay en ti!",
    285: "¡Felicidades! Que tu año esté lleno de realizaciones personales.",
    286: "¡Feliz cumpleaños! Que tus aspiraciones se conviertan en logros.",
    287: "¡Que tu día especial esté lleno de belleza y armonía!",
    288: "¡Feliz cumpleaños! Que la vida te premie por ser quien eres.",
    289: "¡Que este año te traiga mucha claridad y propósito!",
    290: "¡Felicidades! Que tu cumpleaños sea sensacional y único.",
    291: "¡Feliz cumpleaños! Que sigas siendo ese faro de esperanza.",
    292: "¡Que tu día esté lleno de celebración y júbilo!",
    293: "¡Feliz cumpleaños! Que la plenitud sea tu estado permanente.",
    294: "¡Que celebres muchos cumpleaños más con mucho amor!",
    295: "¡Felicidades! Que tu vida siga siendo un viaje maravilloso.",
    296: "¡Feliz cumpleaños! Que cada momento te llene de satisfacción.",
    297: "¡Que tu cumpleaños esté lleno de todo lo que amas!",
    298: "¡Feliz cumpleaños! Que la vida te regale muchas sonrisas.",
    299: "¡Que este nuevo ciclo esté lleno de felicidad absoluta!",
    300: "¡Felicidades! Que tu cumpleaños sea el mejor día del año."
}

def obtener_frase_aleatoria():
    """
    Retorna una frase aleatoria de felicitaciones de cumpleaños del diccionario.
    
    Returns:
        str: Una frase de felicitación de cumpleaños seleccionada al azar.
    """
    clave_aleatoria = random.choice(list(frases_cumpleanos.keys()))
    return frases_cumpleanos[clave_aleatoria]


# Ejemplo de uso
if __name__ == "__main__":
    print("=== Generador de Frases de Cumpleaños ===")
    print(f"\nTotal de frases en el diccionario: {len(frases_cumpleanos)}")
    print("\nAquí tienes 5 frases aleatorias:\n")
    
    for i in range(5):
        print(f"{i+1}. {obtener_frase_aleatoria()}")
